#!/usr/bin/env python3
"""emit_public_numbers: the ONE place any count in the public document comes from.

THE ONE-NUMBER RULE (overseer, 2026-08-12): no count is ever typed into prose. Every count the
public document uses is emitted by this script from the register on a stated date, and included
verbatim. The rule is a prohibition on the BODY, not an appendix convention -- and it is only real
if a script enforces it, which is what `test_public_numbers.py` does.

Run:  python3 emit_public_numbers.py            print the dated block
      python3 emit_public_numbers.py --write    write it to ../PUBLIC_NUMBERS.md
      python3 emit_public_numbers.py --check    regenerate and diff against the written block

The emitted block deliberately contains NO prose interpretation. It is counts and nothing else, so
that a reader can diff it against a fresh run without reading around an argument.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "PUBLIC_NUMBERS.md")

# The date is an ARGUMENT, never `today` -- a block that silently re-dates itself on every run
# cannot be diffed, and "generated on a stated date" is the property the rule needs.
STAMP_DATE = "2026-08-12"

# The collected-test count is a STAMPED CONSTANT, not a live collection.
# WHY (found by the guard on its first run): the emitter originally shelled out to pytest to count
# tests -- so the drift check ran pytest FROM INSIDE pytest, and adding the very test that verifies
# this block changed the number the block asserts. A number-emitter that recurses through its own
# verifier is not a stable reference. The constant is enforced against a real collection by
# test_public_numbers.py::test_the_stamped_test_count_is_true, so it cannot silently rot.
STAMPED_TEST_COUNT = 197


def _load():
    with open(os.path.join(HERE, "claims.json")) as f:
        return json.load(f)["claims"]


def numbers():
    cl = _load()
    grut = [c for c in cl if c.get("ledger_scope", "grut") == "grut"]
    cluster = [c for c in cl if c.get("ledger_scope") == "vacuum-cluster"]

    def net(rows):
        return sum(c.get("ledger_delta", 0) for c in rows
                   if isinstance(c.get("ledger_delta"), int)
                   and not isinstance(c.get("ledger_delta"), bool))

    tiers = {}
    for c in grut:
        tiers[c["tier"]] = tiers.get(c["tier"], 0) + 1

    waivers = [(c["id"], c["ledger_delta"]) for c in grut
               if c.get("laundering_ok") and isinstance(c.get("ledger_delta"), int)
               and c["ledger_delta"] > 0]

    with open(os.path.join(HERE, "sources.json")) as f:
        srcs = [k for k in json.load(f) if not k.startswith("_")]

    calcs = sorted(f for f in os.listdir(os.path.join(ROOT, "calc"))
                   if f.endswith(".py") and not f.startswith("_"))
    tests = sorted(f for f in os.listdir(HERE)
                   if f.startswith("test_") and f.endswith(".py"))

    n_tests = STAMPED_TEST_COUNT

    dispositions = {}
    for c in grut:
        if c.get("disposition"):
            dispositions[c["disposition"]] = dispositions.get(c["disposition"], 0) + 1

    return dict(total=len(cl), n_grut=len(grut), n_cluster=len(cluster),
                net_grut=net(grut), net_cluster=net(cluster), tiers=tiers,
                waivers=waivers, waived_total=sum(d for _, d in waivers),
                n_sources=len(srcs), n_calcs=len(calcs), n_test_files=len(tests),
                n_tests=n_tests, dispositions=dispositions)


def block():
    n = numbers()
    L = []
    L.append(f"<!-- GENERATED by provenance/emit_public_numbers.py on {STAMP_DATE}. "
             f"DO NOT EDIT BY HAND. Regenerate with --write; verify with --check. -->")
    L.append(f"## Register counts, generated {STAMP_DATE}\n")
    L.append("| quantity | value |")
    L.append("|---|---|")
    L.append(f"| claims in `claims.json` (all scopes) | **{n['total']}** |")
    L.append(f"| — of those, GRUT-scope | **{n['n_grut']}** |")
    L.append(f"| — of those, vacuum-cluster scope | **{n['n_cluster']}** |")
    L.append(f"| net underived-input ledger, GRUT scope | **+{n['net_grut']}** |")
    L.append(f"| net underived-input ledger, vacuum-cluster scope | **+{n['net_cluster']}** |")
    L.append(f"| of the GRUT net, carried behind declared waivers | **+{n['waived_total']}** "
             f"across {len(n['waivers'])} claims |")
    L.append(f"| primary sources in `sources.json` | **{n['n_sources']}** |")
    L.append(f"| calculation files in `calc/` | **{n['n_calcs']}** |")
    L.append(f"| test files in `provenance/` | **{n['n_test_files']}** |")
    if n["n_tests"] is not None:
        L.append(f"| tests collected | **{n['n_tests']}** |")
    L.append("")
    L.append(f"### Tier histogram, GRUT scope ({n['n_grut']} claims)\n")
    L.append("| tier | count |")
    L.append("|---|---|")
    for t in ("shown", "derived", "derived-pending", "assumed", "to-derive"):
        L.append(f"| `{t}` | **{n['tiers'].get(t, 0)}** |")
    other = {k: v for k, v in n["tiers"].items()
             if k not in ("shown", "derived", "derived-pending", "assumed", "to-derive")}
    for k, v in sorted(other.items()):
        L.append(f"| `{k}` | **{v}** |")
    L.append("")
    L.append("### Waiver itemization\n")
    L.append("| claim | ledger_delta |")
    L.append("|---|---|")
    for cid, d in sorted(n["waivers"]):
        L.append(f"| `{cid}` | **+{d}** |")
    L.append("")
    if n["dispositions"]:
        L.append("### Closed dispositions, GRUT scope\n")
        L.append("| disposition | count |")
        L.append("|---|---|")
        for k, v in sorted(n["dispositions"].items()):
            L.append(f"| `{k}` | **{v}** |")
        L.append("")
    return "\n".join(L)


def main():
    b = block()
    if "--check" in sys.argv:
        on_disk = open(OUT).read() if os.path.exists(OUT) else ""
        if on_disk.strip() != b.strip():
            print("DRIFT: PUBLIC_NUMBERS.md does not match a fresh run. Regenerate with --write.")
            return 1
        print("public numbers match the register (no drift).")
        return 0
    if "--write" in sys.argv:
        open(OUT, "w").write(b + "\n")
        print(f"wrote {OUT}")
        return 0
    print(b)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
